### ISSUE TITLE
link expired, please update it. 

### ISSUE THREAD

**Issue by cervantes-loves-ai** [shengyangsun/LSTC_VAD#1]
![image](https://github.com/shengyangsun/LSTC_VAD/assets/1273214/004edf40-375a-418d-8f1a-f0675563ded6)

**Comment by ClarkZhu216** [comment]
Have you solved this problem?

**Comment by zuble** [comment]
still a thing

**Comment by shengyangsun** [comment]
Thank you for your interest in our work. All download links have now been updated, and you can proceed to download them again.

**Comment by shengyangsun** [comment]
Thank you for your interest in our work. All download links have now been updated, and you can proceed to download them again.
