### ISSUE TITLE
Regarding feature extraction I3D

### ISSUE THREAD

**Issue by 22ShaliniPriya** [shengyangsun/LSTC_VAD#2]
Dear Sir/Madam,
I had gone through your paper and try to implement it for my college thesis work.

You have given the feature in h5 format. Is it possible to give the feature in npy format? Also the ground truth file is not present for the dataset and the link you have provided for precomputed feature is not available now. 

How do you get this I3D feature in h5 format? Can you provide the code for this? What's the benefit of providing feature in h5 format?

I will be grateful if you provide the solution and the required file and link. Definitely going to cite the paper in my thesis.

**Comment by ClarkZhu216** [comment]
> Dear Sir/Madam, I had gone through your paper and try to implement it for my college thesis work.
> 
> You have given the feature in h5 format. Is it possible to give the feature in npy format? Also the ground truth file is not present for the dataset and the link you have provided for precomputed feature is not available now.
> 
> How do you get this I3D feature in h5 format? Can you provide the code for this? What's the benefit of providing feature in h5 format?
> 
> I will be grateful if you provide the solution and the required file and link. Definitely going to cite the paper in my thesis.

Can you share the I3D feature in h5 format? I can't get it now.

**Comment by shengyangsun** [comment]
Thank you for your interest in our work. All download links have now been updated, and you can proceed to download them again.
